// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

package aiagent

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// The agent CLI already stores every session as JSONL under its own directory, one file per
// session named <session-id>.jsonl, and even records a generated title. So history is read
// from there rather than kept a second time in Wave, which would drift from what `claude
// --resume` actually sees.

// maxHistorySessions caps a listing. Reading a remote store costs one exec per file, and a
// history panel does not need the whole archive.
const maxHistorySessions = 20

// HistorySession is one past conversation.
type HistorySession struct {
	SessionId string `json:"sessionid"`
	// Generated by the CLI; falls back to the first user prompt.
	Title string `json:"title,omitempty"`
	Cwd   string `json:"cwd,omitempty"`
	// Unix seconds of the last write, for ordering.
	ModTime int64 `json:"modtime,omitempty"`
}

// EncodeProjectDir mirrors how the CLI names a project directory: every path separator,
// drive colon and dot becomes a dash. Verified against the directories on disk.
func EncodeProjectDir(cwd string) string {
	repl := strings.NewReplacer(`\`, "-", "/", "-", ":", "-", ".", "-")
	return repl.Replace(cwd)
}

// ListHistory returns past sessions for a working directory, newest first.
func ListHistory(ctx context.Context, connName string, cwd string) ([]HistorySession, error) {
	if cwd == "" {
		return nil, fmt.Errorf("a working directory is required to find its sessions")
	}
	distro := WslDistroFromConn(connName)
	if distro != "" {
		return listHistoryWsl(ctx, distro, cwd)
	}
	if !IsLocalConn(connName) {
		return nil, fmt.Errorf("history is not implemented for connection %q", connName)
	}
	return listHistoryLocal(cwd)
}

func listHistoryLocal(cwd string) ([]HistorySession, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(home, ".claude", "projects", EncodeProjectDir(cwd))
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			// No sessions yet is not an error: it is what a new project looks like.
			return []HistorySession{}, nil
		}
		return nil, err
	}
	rtn := []HistorySession{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".jsonl") {
			continue
		}
		sess := HistorySession{SessionId: strings.TrimSuffix(e.Name(), ".jsonl")}
		if info, err := e.Info(); err == nil {
			sess.ModTime = info.ModTime().Unix()
		}
		if barr, err := os.ReadFile(filepath.Join(dir, e.Name())); err == nil {
			applyTranscriptSummary(&sess, barr)
		}
		rtn = append(rtn, sess)
	}
	sortAndCap(&rtn)
	return rtn, nil
}

func listHistoryWsl(ctx context.Context, distro string, cwd string) ([]HistorySession, error) {
	dir := "$HOME/.claude/projects/" + EncodeProjectDir(cwd)
	// One shell call for the index; the transcripts are fetched separately and only for the
	// newest few, since each one costs another exec.
	script := fmt.Sprintf(`cd %q 2>/dev/null || exit 0; for f in *.jsonl; do [ -e "$f" ] || continue; printf '%%s\t%%s\n' "$f" "$(stat -c %%Y "$f" 2>/dev/null)"; done`, dir)
	out, err := exec.CommandContext(ctx, "wsl.exe", "-d", distro, "-e", "bash", "-lc", script).Output()
	if err != nil {
		return nil, fmt.Errorf("cannot list sessions in %s: %w", distro, err)
	}
	rtn := []HistorySession{}
	for _, line := range strings.Split(strings.ReplaceAll(string(out), "\r", ""), "\n") {
		fields := strings.Split(strings.TrimSpace(line), "\t")
		if len(fields) < 1 || fields[0] == "" {
			continue
		}
		sess := HistorySession{SessionId: strings.TrimSuffix(fields[0], ".jsonl")}
		if len(fields) > 1 {
			var mod int64
			fmt.Sscanf(fields[1], "%d", &mod)
			sess.ModTime = mod
		}
		rtn = append(rtn, sess)
	}
	sortAndCap(&rtn)
	for i := range rtn {
		path := dir + "/" + rtn[i].SessionId + ".jsonl"
		out, err := exec.CommandContext(ctx, "wsl.exe", "-d", distro, "-e", "bash", "-lc", "cat "+path).Output()
		if err != nil {
			continue
		}
		applyTranscriptSummary(&rtn[i], out)
	}
	return rtn, nil
}

func sortAndCap(list *[]HistorySession) {
	sort.Slice(*list, func(i, j int) bool { return (*list)[i].ModTime > (*list)[j].ModTime })
	if len(*list) > maxHistorySessions {
		*list = (*list)[:maxHistorySessions]
	}
}

type transcriptLine struct {
	Type string `json:"type"`
	Cwd  string `json:"cwd"`
	// The CLI writes this as "aiTitle"; verified against a stored transcript.
	AiTitle string `json:"aiTitle"`
	Message *struct {
		Content json.RawMessage `json:"content"`
	} `json:"message"`
}

// applyTranscriptSummary fills in the title and cwd from a stored transcript. The CLI writes
// an "ai-title" line; the first user prompt is the fallback, since a session can be saved
// before a title is generated.
func applyTranscriptSummary(sess *HistorySession, barr []byte) {
	for _, line := range strings.Split(string(barr), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		var tl transcriptLine
		if err := json.Unmarshal([]byte(line), &tl); err != nil {
			continue
		}
		if sess.Cwd == "" && tl.Cwd != "" {
			sess.Cwd = tl.Cwd
		}
		if tl.Type == "ai-title" && tl.AiTitle != "" {
			sess.Title = tl.AiTitle
			// A generated title beats the fallback, so stop looking for one.
			if sess.Cwd != "" {
				return
			}
		}
		if sess.Title == "" && tl.Type == "user" && tl.Message != nil {
			sess.Title = firstUserText(tl.Message.Content)
		}
	}
}

// firstUserText reads a user message body, which is a plain string in most lines and an
// array of blocks in others.
func firstUserText(content json.RawMessage) string {
	var asString string
	if err := json.Unmarshal(content, &asString); err == nil {
		return truncateTitle(asString)
	}
	var blocks []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	}
	if err := json.Unmarshal(content, &blocks); err == nil {
		for _, b := range blocks {
			if b.Type == "text" && b.Text != "" {
				return truncateTitle(b.Text)
			}
		}
	}
	return ""
}

func truncateTitle(s string) string {
	s = strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	if len(s) > 80 {
		return s[:80] + "…"
	}
	return s
}
